nordnet:
  client_id: "your_client_id_here"  # Nordnet Client ID
  client_secret: "your_client_secret_here"  # Nordnet Client Secret
  callback_url: "https://your-redirect-url.com"  # OAuth2 callback URL

  trading_rules:
    # Defines buy/sell actions and risk control mechanisms (stop loss, trailing stop loss, take profit).
    # Safe, medium, and risky levels provide different risk thresholds and triggers for buying/selling stocks.

    safe:
      buy:
        drop_percent: 2
      sell:
        rise_percent: 5
      stop_loss:
        drop_percent: 8
      trailing_stop_loss:
        trail_percent: 5
      take_profit:
        rise_percent: 15

    medium:
      buy:
        drop_percent: 5
      sell:
        rise_percent: 10
      stop_loss:
        drop_percent: 10
      take_profit:
        rise_percent: 20

    risky:
      buy:
        drop_percent: 10
      sell:
        rise_percent: 20
      volatility_threshold:
        high_volatility: 10
      moving_average_crossover:
        short_term_period: 50
        long_term_period: 200

  monitoring:
    # Controls the frequency of stock price monitoring and the sensitivity to price changes.
    # Low, medium, and high levels correspond to different intervals and thresholds for triggering alerts.

    low:
      interval_seconds: 60
      alert_threshold: 0.01
    medium:
      interval_seconds: 30
      alert_threshold: 0.03
    high:
      interval_seconds: 10
      alert_threshold: 0.05
