nordnet:
  client_id: "your_client_id_here"  # Nordnet Client ID
  client_secret: "your_client_secret_here"  # Nordnet Client Secret
  callback_url: "https://your-redirect-url.com"  # OAuth2 callback URL
